Fixes
moves-rwth/storm pull request #163
Opened 2021-11-05 09:14 UTC by jipspel

- Improve implementation of fixed choices for MDPs
- fix several warnings

2021-11-09 06:54 UTC, tquatmann requested changes
I haven't looked through the monotonicity details with great care, but the fixes there seem valid.

I'm going to run some  benchmarks to see if the changes in svi and ovi affect performance.

2021-11-09 06:54 UTC, tquatmann commented on src/storm/solver/helper/OptimisticValueIterationHelper.cpp
> +                            newXi = multiplyRow(i, b[i + scheduler.get().at(i)], x);
This currently multiplies the `i`th row, right? shouldn't it be something like
```suggestion
                            auto row = i + scheduler.get().at(i);
                            newXi = multiplyRow(row, b[row], x);
```
same applies to similar occurrences below.

2021-11-09 06:54 UTC, tquatmann commented on src/storm/solver/TopologicalMinMaxLinearEquationSolver.cpp
> +            // Only for this one we do something with the fixed choices
This comment seems to be a bit out of context

2021-11-09 06:54 UTC, tquatmann commented on src/storm/solver/TopologicalMinMaxLinearEquationSolver.cpp
>                  storm::storage::BitVector choiceFixedForStateSCC(sccRowGroups.getNumberOfSetBits());
This is shorter compared to the computation below:
```suggestion
                storm::storage::BitVector choiceFixedForStateSCC = this->choicesFixedForRowGroup % sccRowGroups;
```
Although I think `choiceFixedForStateSCC` is not used? Maybe there is a typo below.

2021-11-09 06:54 UTC, tquatmann commented on src/storm/solver/TopologicalMinMaxLinearEquationSolver.cpp
> +                    }
Use `storm::utility::vector::setVectorValues` ?

2021-11-09 06:54 UTC, tquatmann commented on src/storm/solver/TopologicalMinMaxLinearEquationSolver.cpp
> +                    }
And I think here is the typo I mentioned before. It should refer to `choiceFixedForStateSCC`, right?

2021-11-09 13:02 UTC, jipspel commented on src/storm/solver/IterativeMinMaxLinearEquationSolver.cpp
> +                    // Throws error when choices for scheduler are fixed
I'll remove this comment as it is incorrect.

2021-11-09 13:03 UTC, jipspel commented on src/storm/solver/IterativeMinMaxLinearEquationSolver.cpp
> +                    // Throws error when choices for scheduler are fixed
I'll remove the comment, however solveEquationsIntervalIteration does throw a NotImplementedException.

2021-11-09 13:06 UTC, jipspel commented on src/storm/solver/IterativeMinMaxLinearEquationSolver.cpp
> +                // TODO: integrate fixed choices for the scheduler for a rowgroup in multiplier
added a storm_log_throw

2021-11-09 13:15 UTC, jipspel commented on src/storm/storage/jani/eliminator/FunctionEliminator.cpp
uhhhh no idea I'll look into it

2021-11-09 13:42 UTC, jipspel commented on src/storm/solver/helper/SoundValueIterationHelper.cpp
> +                        auto rowGroupIndex = groupStartIt - rowGroupIndices->rbegin() - 1;
I don't understand the problem. We calculate the rowGroupIndex (which is the state number?) and then pick the correct row based on the current groupStart and the choice for the statenumber.

2021-11-10 08:02 UTC, tquatmann commented on src/storm/solver/helper/SoundValueIterationHelper.cpp
> +                        auto rowGroupIndex = groupStartIt - rowGroupIndices->rbegin() - 1;
When there are `n` states with indices `0, 1, ..., n-1`, the iteration (i.e. `groupStartIt`) refers to state `n-1` first, then `n-2`, ... all the way down to state 0 in the last iteration.  Notice that we have the reverse iterators via `rbegin()` (and not `begin()` here.

However, if I see this correctly, the `rowGroupIndex` starts with `0` in the first iteration and then counts upwards to `n-1` in the last iteration.

Is it clearer now? It's probably better to just initialize rowGroupIndex with `n` and do `--rowGroupIndex;` at the beginning of each iteration. Or I am completely wrong here 😅

2021-11-10 08:18 UTC, tquatmann commented on src/storm/solver/LpMinMaxLinearEquationSolver.cpp
> +                    }
The `auto` in line 71 creates a separate variable `rowIndex` that runs out of scope in line 72. I guess you wanted to set the `rowIndex` variable from line 68 instead? Anyway, I'd suggest to do it like this:
```suggestion
                uint64_t rowIndex, rowGroupEnd;
                if (this->choiceFixedForRowGroup && this->choiceFixedForRowGroup.get()[rowGroup]) {
                    rowIndex = this->A->getRowGroupIndices()[rowGroup] + this->getInitialScheduler()[rowGroup];
                    rowGroupEnd = rowIndex + 1;
                } else {
                    rowIndex = this->A->getRowGroupIndices()[rowGroup];
                    rowGroupEnd = this->A->getRowGroupIndices()[rowGroup + 1];
                }
                for (; rowIndex < rowGroupEnd; ++rowIndex) {
```
Then, the `if` block in line 87 below can be removed and we check for fixed choices less often.

2021-11-10 08:30 UTC, tquatmann requested changes

2021-11-10 08:30 UTC, tquatmann commented on src/storm/solver/TopologicalMinMaxLinearEquationSolver.cpp
> +                    storm::utility::vector::setVectorValues(sccInitChoices, this->choiceFixedForStateScc.get(), 0);
```suggestion
                    storm::utility::vector::setVectorValues(sccInitChoices, choiceFixedForStateScc, 0);
```

2021-11-10 08:30 UTC, tquatmann commented on src/storm/solver/helper/OptimisticValueIterationHelper.cpp
> +                                x[i] = multiplyRow(i, b[i + scheduler.get().at(i)], x);
```suggestion
                                auto row = i + scheduler.get().at(i);
                                newXi = multiplyRow(row, b[row], x);
```

2021-11-10 11:03 UTC, jipspel commented on src/storm/solver/helper/SoundValueIterationHelper.cpp
> +                        auto rowGroupIndex = groupStartIt - rowGroupIndices->rbegin() - 1;
ahh yeah now I get it :)

2021-11-11 09:59 UTC, tquatmann approved these changes

2021-11-11 10:16 UTC, merged